EZ-University/Xiang_Cong_ez_university/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView


urlpatterns = [

    path('',
         RedirectView.as_view(
             pattern_name='about_urlpattern',
             permanent=False
         )),

    path('login/',
         LoginView.as_view(template_name='courseinfo/login.html'),
         name='login_urlpattern'
         ),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),

    path('about/',
         TemplateView.as_view(
             template_name='courseinfo/about.html'),
         name='about_urlpattern'
    ),

    path('admin/', admin.site.urls),

    path('', include('courseinfo.urls'))

]

EZ-University/courseinfo/urls.py
from django.urls import path

from .views import (
    InstructorList,
    SectionList,
    CourseList,
    SemesterList,
    StudentList,
    RegistrationList,
    InstructorDetail,
    InstructorUpdate,
    InstructorDelete,
    SectionDetail,
    CourseDetail,
    SemesterDetail,
    StudentDetail,
    RegistrationDetail,
    InstructorCreate,
    SectionCreate,
    SectionUpdate,
    SectionDelete,
    CourseCreate,
    CourseUpdate,
    CourseDelete,
    SemesterCreate,
    SemesterUpdate,
    SemesterDelete,
    StudentCreate,
    StudentUpdate,
    StudentDelete,
    RegistrationCreate,
    RegistrationUpdate,
    RegistrationDelete,
)

urlpatterns = [

    path('instructor/',
         InstructorList.as_view(),
         name='courseinfo_instructor_list_urlpattern'),

    path('instructor/<int:pk>/',
        InstructorDetail.as_view(),
        name='courseinfo_instructor_detail_urlpattern'),

    path('instructor/create/',
         InstructorCreate.as_view(),
         name='courseinfo_instructor_create_urlpattern'),

    path('instructor/<int:pk>/update/',
         InstructorUpdate.as_view(),
         name='courseinfo_instructor_update_urlpattern'),

    path('instructor/<int:pk>/delete/',
         InstructorDelete.as_view(),
         name='courseinfo_instructor_delete_urlpattern'),

    path('section/',
         SectionList.as_view(),
         name='courseinfo_section_list_urlpattern'),

    path('section/<int:pk>/',
        SectionDetail.as_view(),
        name='courseinfo_section_detail_urlpattern'),

    path('section/create/',
         SectionCreate.as_view(),
         name='courseinfo_section_create_urlpattern'),

    path('section/<int:pk>/update/',
         SectionUpdate.as_view(),
         name='courseinfo_section_update_urlpattern'),

    path('section/<int:pk>/delete/',
         SectionDelete.as_view(),
         name='courseinfo_section_delete_urlpattern'),

    path('course/',
         CourseList.as_view(),
         name='courseinfo_course_list_urlpattern'),

    path('course/<int:pk>/',
        CourseDetail.as_view(),
        name='courseinfo_course_detail_urlpattern'),

    path('course/create/',
         CourseCreate.as_view(),
         name='courseinfo_course_create_urlpattern'),

    path('course/<int:pk>/update/',
         CourseUpdate.as_view(),
         name='courseinfo_course_update_urlpattern'),

    path('course/<int:pk>/delete/',
         CourseDelete.as_view(),
         name='courseinfo_course_delete_urlpattern'),

    path('semester/<int:pk>/',
        SemesterDetail.as_view(),
        name='courseinfo_semester_detail_urlpattern'),

    path('semester/',
         SemesterList.as_view(),
         name='courseinfo_semester_list_urlpattern'),

    path('semester/create/',
         SemesterCreate.as_view(),
         name='courseinfo_semester_create_urlpattern'),

    path('semester/<int:pk>/update/',
         SemesterUpdate.as_view(),
         name='courseinfo_semester_update_urlpattern'),

    path('semester/<int:pk>/delete/',
         SemesterDelete.as_view(),
         name='courseinfo_semester_delete_urlpattern'),

    path('student/',
         StudentList.as_view(),
         name='courseinfo_student_list_urlpattern'),

    path('student/<int:pk>/',
        StudentDetail.as_view(),
        name='courseinfo_student_detail_urlpattern'),

    path('student/create/',
         StudentCreate.as_view(),
         name='courseinfo_student_create_urlpattern'),

    path('student/<int:pk>/update/',
         StudentUpdate.as_view(),
         name='courseinfo_student_update_urlpattern'),

    path('student/<int:pk>/delete/',
         StudentDelete.as_view(),
         name='courseinfo_student_delete_urlpattern'),

    path('registration/',
         RegistrationList.as_view(),
         name='courseinfo_registration_list_urlpattern'),

    path('registration/<int:pk>/',
         RegistrationDetail.as_view(),
         name='courseinfo_registration_detail_urlpattern'),

    path('registration/create/',
         RegistrationCreate.as_view(),
         name='courseinfo_registration_create_urlpattern'),

    path('registration/<int:pk>/update/',
         RegistrationUpdate.as_view(),
         name='courseinfo_registration_update_urlpattern'),

    path('registration/<int:pk>/delete/',
         RegistrationDelete.as_view(),
         name='courseinfo_registration_delete_urlpattern'),

]

EZ-University/courseinfo/models.py
from django.db import models
from django.urls import reverse


class Period(models.Model):
    period_id = models.AutoField(primary_key=True)
    period_sequence = models.IntegerField(unique=True)
    period_name = models.CharField(max_length=45,unique=True)

    def __str__(self):
        return '%s' % self.period_name

    class Meta:
        ordering = ['period_sequence']


class Year(models.Model):
    year_id = models.AutoField(primary_key=True)
    year = models.IntegerField(unique=True)

    def __str__(self):
        return '%s' % self.year

    class Meta:
        ordering = ['year']


class Semester(models.Model):
    semester_id = models.AutoField(primary_key=True)
    year = models.ForeignKey(Year, related_name='semesters', on_delete=models.PROTECT)
    period = models.ForeignKey(Period, related_name='semesters', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.year.year, self.period.period_name)

    def get_absolute_url(self):
        return reverse('courseinfo_semester_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('courseinfo_semester_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_semester_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['year__year', 'period__period_sequence']
        unique_together = ('year', 'period')


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_number = models.CharField(max_length=20)
    course_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.course_number, self.course_name)

    def get_absolute_url(self):
        return reverse('courseinfo_course_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('courseinfo_course_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_course_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['course_number', 'course_name']
        unique_together = (('course_number', 'course_name'),)


class Instructor(models.Model):
    instructor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('courseinfo_instructor_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_instructor_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse(
            'courseinfo_instructor_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['last_name', 'first_name']
        unique_together = (('last_name', 'first_name'),)


class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    nickname = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.nickname == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.nickname)
        return result

    def get_absolute_url(self):
        return reverse('courseinfo_student_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_student_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_student_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'nickname']
        unique_together = (('last_name', 'first_name', 'nickname'),)


class Section(models.Model):
    section_id = models.AutoField(primary_key=True)
    section_name = models.CharField(max_length=10)
    semester = models.ForeignKey(Semester, related_name='sections', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, related_name='sections', on_delete=models.PROTECT)
    instructor = models.ForeignKey(Instructor, related_name='sections', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s (%s)' % (self.course.course_number, self.section_name, self.semester.__str__())

    def get_absolute_url(self):
        return reverse('courseinfo_section_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_section_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_section_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['course__course_number', 'section_name', 'semester__semester_name']
        unique_together = (('semester', 'course', 'section_name'),)


class Registration(models.Model):
    registration_id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, related_name='registrations',  on_delete=models.PROTECT)
    section = models.ForeignKey(Section, related_name='registrations',  on_delete=models.PROTECT)

    def __str__(self):
        return '%s / %s' % (self.section, self.student)

    def get_absolute_url(self):
        return reverse('courseinfo_registration_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_registration_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_registration_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['section', 'student']
        unique_together = (('section', 'student'),)

EZ-University/courseinfo/forms.py
from django import forms

from courseinfo.models import Instructor, Section, Course, Semester, Student, Registration


class InstructorForm(forms.ModelForm):
    class Meta:
        model = Instructor
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = '__all__'

    def clean_section_name(self):
        return self.cleaned_data['section_name'].strip()


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

    def clean_course_number(self):
        return self.cleaned_data['course_number'].strip()

    def clean_course_name(self):
        return self.cleaned_data['course_name'].strip()


class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = '__all__'

    def clean_semester_name(self):
        return self.cleaned_data['semester_name'].strip()


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

    def clean_nickname(self):
        if len(self.cleaned_data['nickname']) == 0:
            result = self.cleaned_data['nickname']
        else:
            result = self.cleaned_data['nickname'].strip()
        return result


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = '__all__'

EZ-University/courseinfo/templates/courseinfo/course_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Course - {{ course }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ course }}</h2>
    <ul class="inline">
        {% if perms.courseinfo.change_course %}
        <li>
          <a
              href="{{ course.get_update_url }}"
              class="button">
            Edit Course</a></li>
        {% endif %}
        {% if perms.courseinfo.delete_course %}
        <li>
          <a
              href="{{ course.get_delete_url }}"
              class="button">
            Delete Course</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Course Number:</th>
                <td>{{ course.course_number }}</td>
            </tr>
            <tr>
                <th>Course Name:</th>
                <td>{{ course.course_name }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Sections</h3>
        <ul>
            {% for section in section_list %}
                <li>
                    <a href="{{ section.get_absolute_url }}">{{ section }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no sections for this course.</em></li>
            {% endfor %}
        </ul>
    </section>
  </div></div> <!-- row -->

</article>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/course_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Course List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_course %}
    <a
        href="{% url 'courseinfo_course_create_urlpattern'  %}"
        class="button button-primary">
      Create New Course</a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h2>Course List</h2>
    {% if perms.courseinfo.add_course %}
    <div class="mobile">
      <a
          href="{% url 'courseinfo_course_create_urlpattern' %}"
          class="button button-primary">
        Create New Course</a>
    </div>
    {% endif %}
  <ul>
    {% for course in course_list %}
      <li>
        <a href="{{ course.get_absolute_url }}">
          {{ course }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no courses available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/course_refuse_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Error Deleting Course
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Course</h2>
        <p>
            You may not delete course{{ course }}. This
            course is currently assigned to the following sections:
        </p>

        <ul>
            {% for section in sections %}
            <li><a href="{{ sections.get_absolute_url}}">{{ section }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'courseinfo_course_list_urlpattern' %}">Course List</a>
        </p>
    </div>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/instructor_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Instructor - {{ instructor }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ instructor }}</h2>
                <ul class="inline">
                    {% if perms.courseinfo.change_instructor %}
                        <li>
                            <a href="{{ instructor.get_update_url }}"
                               class="button">
                                Edit Instructor</a></li>
                    {% endif %}
                    {% if perms.courseinfo.delete_instructor %}
                        <li>
                            <a href="{{ instructor.get_delete_url }}"
                               class="button">
                                Delete Instructor</a></li>
                    {% endif %}
                </ul>

                <section>
                    <table>
                        <tr>
                            <th>First Name:</th>
                            <td>{{ instructor.first_name }}</td>
                        </tr>
                        <tr>
                            <th>Last Name:</th>
                            <td>{{ instructor.last_name }}</td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Sections</h3>
                    <ul>
                        {% for section in section_list %}
                            <li>
                                <a href="{{ section.get_absolute_url }}">{{ section }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no sections for this instructor.</em></li>
                        {% endfor %}
                    </ul>
                </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/login.html
{% extends 'courseinfo/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/registration_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Registration - {{ registration }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ student }}</h2>
    <ul class="inline">
        {% if perms.courseinfo.change_student %}
        <li>
          <a href="{{ registration.get_update_url }}"
          class="button">
            Edit Registration</a></li>
        {% endif %}
        {% if perms.courseinfo.delete_student %}
          <a href="{{ registration.get_delete_url }}"
          class="button">
            Delete Registration</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Student:</th>
                <td><a href="{{ student.get_absolute_url }}">{{ student }}</a></td>
            </tr>
            <tr>
                <th>Section:</th>
                <td><a href="{{ section.get_absolute_url }}">{{ section }}</a></td>
            </tr>
        </table>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/registration_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Registration List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_student %}
      <a href="{% url 'courseinfo_registration_create_urlpattern' %}"
         class="button button-primary">
        Create New Registration</a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h2>Registration List</h2>
    {% if perms.courseinfo.add_student %}
    <div class="mobile">
      <a href="{% url 'courseinfo_registration_create_urlpattern' %}"
         class="button button-primary">
        Create New Registration</a>
    </div>
    {% endif %}
    <ul>
        {% for registration in registration_list %}
            <li>
                <a href="{{ registration.get_absolute_url }}">{{ registration }}</a>
            </li>
        {% empty %}
            <li><em>There are currently no registrations available.</em></li>
        {% endfor %}
    </ul>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/section_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Section
{% endblock %}

{% block content %}
    <form
        action="{{ section.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete the section{{ section }}?
        </p>
        <a href="{{ section.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Section</button>

    </form>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/section_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Section
{% endblock %}

{% block content %}
    <form
        action="{{ section.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Section</button>
    </form>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/section_refuse_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Error Deleting Section
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Section</h2>
        <p>
            You may not delete section{{ section }}. This
            section is currently has the following registered students:
        </p>

        <ul>
            {% for registration in registrations %}
            <li><a href="{{ registration.get_absolute_url}}">{{ registration.student }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'courseinfo_section_list_urlpattern' %}">Section List</a>
        </p>
    </div>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/semester_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Semester
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_semester_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Semester</button>
    </form>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/semester_refuse_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Error Deleting Semester
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Semester</h2>
        <p>
            You may not delete semester{{ semester }}. This
            semester is currently assigned to the following sections:
        </p>

        <ul>
            {% for section in sections %}
            <li><a href="{{ sections.get_absolute_url}}">{{ section }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'courseinfo_semester_list_urlpattern' %}">Semester List</a>
        </p>
    </div>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/student_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Student
{% endblock %}

{% block content %}
    <form
            action="{% url 'courseinfo_student_create_urlpattern' %}"
            method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Student</button>
    </form>
{% endblock %}

EZ-University/courseinfo/templates/courseinfo/student_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Student
{% endblock %}

{% block content %}
    <form
            action = "{{ student.get_update_url }}"
            method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Update Student</button>
    </form>
{% endblock %}